### ISSUE TITLE
Native Canvas MathJax

### ISSUE THREAD

**Issue by siwelwerd** [StevenClontz/checkit#19]
@StevenClontz noticed that you can get to Canvas's MathJax via for example

`<img class="equation_image" src="/equation_images/codeGoesHere" />`
or 
`<img class="equation_image" src="/equation_images/z'%253DR-%255Cfrac%257BRz%257D%257Bv%257Du%255Cleft(t-a%255Cright)%255Chspace%257B1em%257Dz(0)%253D0" />`

So it looks like for example, %253D is the ecnoding of %3D which is =.  I believe the python library urllib can be used to automate this https://docs.python.org/3/library/urllib.html . This would enable the generated QTI to use the native Canvas MathJax, instead of the external website CodeCogs as it does currently. Perhaps we could leave a flag for the user to select CodeCogs if they wanted, but relying on an external website adds an additional point of failure.

**Comment by StevenClontz** [comment]
It's also plausible that URL encoding isn't necessary (we don't do it for CodeCogs right now).

If anyone needs the CodeCogs solution I can leave it in as an option, but I'll probably just remove it if Canvas's own engine does fine.

**Comment by siwelwerd** [comment]
I was thinking it might be useful to have the CodeCogs option when supporting other LMS's (e.g. D2L) that might not do MathJax.

**Comment by StevenClontz** [comment]
This is sort-of implemented, but we use URLs like <https://usaonline.southalabama.edu/equation_images/%7By'%7D%20=%20-%5Cfrac%7B1%7D%7B3%7D%20%5C,%20t%20+%20%5Cfrac%7B1%7D%7B15%7D%20%5C,%20%7By%7D>. 

But that said, it seems that <https://canvas.instructure.com/equation_images/%7By'%7D%20=%20-%5Cfrac%7B1%7D%7B3%7D%20%5C,%20t%20+%20%5Cfrac%7B1%7D%7B15%7D%20%5C,%20%7By%7D> points to the same AWS service, so that seems to be the "correct" way to implement this in general.

I may break out CodeCogs again when I work on #24 D2L exporting, but once I swap the USA canvas domain with the generic Canvas domain, I think this is closed.
